### ISSUE TITLE
Cannot proceed to enter payment details when coupon applied

### ISSUE THREAD

**Issue by whitemint** [woothemes/woocommerce-gateway-mijireh-checkout#2]
When applying a coupon (in this case "thanks10") it accepts the code and adds the discount. but when you click through to enter your card details, the following error occurs, which prevents the customer from entering card details. The error that appears is below:

•Mijireh error:{"total":["must add up correctly to the items, discount, tax and shipping costs"]}Mijireh_Order Object ( [_data:protected] => Array ( [partner_id] => woo [order_number] => [mode] => [status] => [order_date] => [ip_address] => [checkout_url] => [total] => 18 [return_url] => http://www.whitemint.co.uk/wc-api/WC_Gateway_Mijireh/ [items] => Array ( [0] => Array ( [name] => Order 2442 - Personalised Mr & Mrs Large Glass Kilner Jar x 1 [price] => 18.00 [quantity] => 1 [sku] => [total] => 18.00 ) ) [email] => maria_litras@hotmail.com [first_name] => Maria [last_name] => Litras [meta_data] => Array ( [wc_order_id] => 2442 ) [tax] => [shipping] => [discount] => 2 [shipping_address] => Array ( [first_name] => Maria [last_name] => Litras [street] => 89 Albert Embankment [city] => London [state_province] => London [zip_code] => EN4 8LE [country] => GB [company] => Macmillan Cancer Support [apt_suite] => [phone] => ) [billing_address] => Array ( [first_name] => Maria [last_name] => Litras [street] => 52 Ferney Road [city] => East Barnet [state_province] => Hertfordshire [zip_code] => EN4 8LE [country] => GB [company] => [apt_suite] => [phone] => 07443520342 ) [show_tax] => ) [_errors:protected] => Array ( ) )

**Comment by whitemint** [comment]
Hi Claudio, Mijreh have replied to my issue with the following: 
I'm sorry, you will have to go to WooCommerce about this error. The Mijireh service takes all the information given to us, but if the numbers do not add up, then we reject the transaction. You can see from the information in your email that the individual parts do not add up to the total given: (items) 18.00 + (tax) 0.00 + (shipping) 0.00 - (discount) 2 = 16.00. Yet the transaction says the total should be 18.00. See this screen shot for where I got those individual numbers: http://my.jetscreenshot.com/23659/20150213-ysaj-60kb.jpg

**Comment by claudiosmweb** [comment]
Please show me your coupon settings.

**Comment by whitemint** [comment]
Hi Claudio as requested, screenshots attached
![coupon3](https://cloud.githubusercontent.com/assets/10992182/6190294/b84c064a-b398-11e4-99f9-95cb290ccca1.jpg)
![coupon2](https://cloud.githubusercontent.com/assets/10992182/6190295/b84dbfa8-b398-11e4-96ae-2f3f98464080.jpg)
![coupon1](https://cloud.githubusercontent.com/assets/10992182/6190296/b856c4f4-b398-11e4-84d5-53fbb0635a32.jpg)

**Comment by claudiosmweb** [comment]
@whitemint fixed in 1.0.2.
Thank you for reporting this.

**Comment by Deaner666** [comment]
My customers have started getting this problem when applying cart % discounts in the last few days. Not sure what update has triggered it:

```Mijireh error:{"total":["must add up correctly to the items, discount, tax and shipping costs"]}Mijireh_Order Object ( [_data:protected] => Array ( [partner_id] => woo [order_number] => [mode] => [status] => [order_date] => [ip_address] => [checkout_url] => [total] => 34.73 [return_url] => http://www.print-2-media.com/wc-api/WC_Gateway_Mijireh/ [items] => Array ( [0] => Array ( [name] => Foamex Signs [price] => 18.82 [quantity] => 1 [sku] => rigfo0001 [total] => 18.82 ) ) [email] => dave@moortor-design.co.uk [first_name] => Dave [last_name] => Dean [meta_data] => Array ( [wc_order_id] => 51048 ) [tax] => 5.79 [shipping] => 12 [discount] => 1.882 [shipping_address] => Array ( [first_name] => Dave [last_name] => Dean [street] => 5 Ferndale Terrace [city] => Liskeard [state_province] => [zip_code] => PL14 6DT [country] => GB [company] => [apt_suite] => Old Road [phone] => ) [billing_address] => Array ( [first_name] => Dave [last_name] => Dean [street] => 5 Ferndale Terrace [city] => Liskeard [state_province] => [zip_code] => PL14 6DT [country] => GB [company] => [apt_suite] => Old Road [phone] => 07850502045 ) [show_tax] => 1 ) [_errors:protected] => Array ( ) )```

**Comment by PeterGrand** [comment]
I'm seeing this error as well with the following cart:
Item A $13.49
Item B $14.49
Subtotal $27.98

Coupon: -$6.75 (50% off Item A)
Shipping: Free
Sales Tax: $1.59
Total: $22.83

If I add up the total manually, it comes out to $22.82.

If I take Item B out of the cart, the math all works out and listed total is accurate.

**Comment by vbampton** [comment]
I'm seeing the same. Rolling back to WC 2.3.8 solves it as a temporary measure.

**Comment by PeterGrand** [comment]
I opened an [issue for this](https://github.com/woothemes/woocommerce/issues/8291) on the main WooCommerce repo and it has been confirmed to be fixed in versioin 2.4.
