### ISSUE TITLE
64 character limit of the Mijireh product/invoice description

### ISSUE THREAD

**Issue by slash1andy** [woothemes/woocommerce-gateway-mijireh-checkout#3]
When the items are input including tax, the plugin combines all items in the order into one line item to send to Mijireh to alleviate rounding issues. It concatenates the descriptions, but if there are more than a few items, it can go over the 64 character limit in the description. I think we just need to limit the description length.

**Comment by slash1andy** [comment]
https://woothemes.zendesk.com/agent/tickets/281489

**Comment by roykho** [comment]
I am not able to replicate this issue.  I used a ridiculous amount of characters >64 as seen here ![](http://cld.wthms.co/1aGIm+) and the order went through just fine. cc: @ChromeOrange

**Comment by roykho** [comment]
So perhaps the limit is NOT with Mijireh but with the payment gateway they're using?

**Comment by slash1andy** [comment]
They are using eWay Rapid 3.0 @roykho

**Comment by slash1andy** [comment]
It's an eWay error:  	Invalid Payment InvoiceDescription

https://eway.io/api-v3/#validation-response-codes
