### ISSUE TITLE
{"total":["must add up correctly to the items, discount, tax and shipping costs"]}

### ISSUE THREAD

**Issue by vbampton** [woothemes/woocommerce-gateway-mijireh-checkout#4]
With WC 2.3.9 or later, I get {"total":["must add up correctly to the items, discount, tax and shipping costs"]} with the following cart:

Product - £14.95
Discount - 10%
Total - £12.97

PayPal works correctly with 2.3.10. I have to roll back to 2.3.8 to get Mijireh to work.

**Comment by mikejolley** [comment]
This is related to #6 

We need to clean up rounding and ensure totals add up. Some of the logic in PayPal standard can be adapted for this.

**Comment by justinshreve** [comment]
Hi, I've had some trouble reproducing this (though, while researching I've seen a couple other reports, including #6).

I was hoping you could give me a few more details about how you have everything setup so I can make sure any changes I make actually resolve the problem :smiley: . Specifically, could you let me know how you have discounts configured? Is it a cart %, item %? How are taxes setup? I've tried a few different combinations but have not been able to get the error yet.

**Comment by vbampton** [comment]
Hi Justin

I've since rolled back to get it to work and it's a live site so I can't risk upgrading right now, but I can tell you what I remember...

This was with a 10% cart discount.  The code was its-done, set to limit to one use per user, individual use only.  Very standard coupon.  You can have screenshots if it would help.

The product was a variation, virtual (eBook) costing £14.95.  I didn't get the same problem with the other variation, which was a physical book costing £29.95.

Main Settings:
Base location - UK.
I tried it with Enable tax calculations on and off. Usually off.
I tried it with Yes I will enter prices inclusive of tax and No I will enter prices exclusive of tax.
I set the shipping tax class to Zero Rate.
I tried it with  Round tax at subtotal level, instead of rounding per line checked and unchecked.
I think I tried every combination of those settings.
Display Prices During Cart and Checkout: is set to Excluding Tax.
Display Tax Totals: as both As a Single Total and Itemized.

Hope that helps!

**Comment by justinshreve** [comment]
Thanks for the extra info!
